Repository javierbrea/eslint-plugin-boundaries, pull requests merged in 2020-12, with the labels that each got.

#66 BUGFIX: dependencyInfo.name might be null
  src/rules/no-external.js
Labels: bug

#69 Add unit test for fix #65
  CHANGELOG.md
  test/src/rules/no-external.spec.js
Labels: bug, tests

#70 Release v1.1.1
  .github/workflows/build.yml
  .github/workflows/publish-to-github.yml
  .github/workflows/publish-to-npm.yml
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  sonar-project.properties
  src/rules/no-external.js
  test/src/rules/no-external.spec.js
Labels: CI-CD, bug, dependencies
